---
- name: Install dependencies
  yum: name={{ item }} state=installed
  with_items:
   - gcc
   - python-pip
   - python-devel
   - postgresql93-devel

- name: Install wal-e
  pip: name=wal-e state=present

- name: Install variables for WAL-E
  template: src=sysconfig.j2 dest=/etc/sysconfig/wal-e owner=postgres group=postgres mode=0640

