---
- name: Make Ansible Facts directory
  file: path=/etc/ansible/facts.d state=directory

- name: Install Postgres
  yum: name={{ item }} state=installed
  with_items:
   - postgresql93
   - postgresql93-libs
   - postgresql93-devel
   - postgresql93-server
   - postgresql93-contrib
   - python-psycopg2
   - perl-Digest-SHA

- name: Make Ansible Facts directory
  file: path=/etc/facts.d state=directory

- name: Install recovery template
  template: src=pg_recovery_template.conf.j2 dest=/usr/local/etc/pg_recovery_template.conf

- name: Initialise the DB server
  command: creates=/var/lib/pgsql/9.3/data/PG_VERSION /etc/init.d/postgresql-9.3 initdb

# This include sets up the following variables:
#  - postgres_status: Is this server a master or slave?
#  - postgres_master: Which server is the master?
- include: get_status.yml

- include: master.yml
  when: postgres_status == "master"

- include: slave.yml
  when: postgres_status == "slave"


