---
- name: Install Postgres
  yum: name={{ item }} state=installed
  with_items:
   - postgresql93
   - postgresql93-libs
   - postgresql93-devel
   - postgresql93-server
   - postgresql93-contrib
   - python-psycopg2

- name: Initialise the DB server
  command: creates=/var/lib/pgsql/9.3/data/PG_VERSION /etc/init.d/postgresql-9.3 initdb

- name: Configure Postgres
  template: src={{ item }}.j2 dest=/var/lib/pgsql/9.3/data/{{ item }} owner=postgres group=postgres mode=600
  with_items:
   - postgresql.conf
   - pg_hba.conf

- name: Start Postgres
  service: name=postgresql-9.3 state=started enabled=yes

- name: Create Postgres Replication User
  postgresql_user:
    name: repl
    password: replpass
    role_attr_flags: REPLICATION
  sudo_user: postgres

- name: Create Postgres pgPool User
  postgresql_user:
    name: pgpool
    password: poolpass
    role_attr_flags: LOGIN
  sudo_user: postgres

